name: Kobo Book Downloader
version: "v0.6.0"
slug: kobo-book-downloader
description: Download Kobo ebooks and audiobooks
url: https://github.com/subdavis/kobo-book-downloader
arch:
  - aarch64
  - amd64
init: false
map:
  - media:rw
  - share:rw
  - addon_config:rw
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web UI
webui: http://[HOST]:[PORT:5000]
options:
  download_path: /media/kobo-books
  log_level: info
schema:
  download_path: str
  log_level: list(debug|info|warning|error)
